language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
env:
  - RIAK_VERSION="1.4.12-1"
matrix:
  include:
    # Riak 2.0 sometimes doesn't have enough file descriptors:
    # https://github.com/travis-ci/travis-ci/issues/3328
    # Until that's fixed, don't build against new Riak.
    # # Test against the Travis-provided version of Riak (currently 2.0.x).
    # # This is a separate matrix inclusion to avoid spawning unnecessary builds.
    # - python: "2.7"
    #   env: RIAK_VERSION=current
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - python: "pypy"
      # PYPY_GC_MAX_PINNED=0 works around an obscure gc bug in pypy<=2.6.0
      env: NO_COVERAGE="1" RIAK_VERSION="1.4.12-1" PYPY_GC_MAX_PINNED=0 PYPY_VERSION="2.6.0"

services:
  - postgresql
  - redis-server
before_install:
  # Set up an appropriate version of Riak.
  - sudo utils/setup_travis_riak.sh "${RIAK_VERSION}"
install:
  - if [ ! -z "$PYPY_VERSION" ]; then deactivate; curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash; export PATH="$HOME/.pyenv/bin:$PATH"; eval "$(pyenv init -)"; eval "$(pyenv virtualenv-init -)"; which pyenv; fi
  - if [ ! -z "$PYPY_VERSION" ]; then pyenv install pypy-$PYPY_VERSION; pyenv global pypy-$PYPY_VERSION; virtualenv -p $(which python) ~/env-pypy-$PYPY_VERSION; source ~/env-pypy-$PYPY_VERSION/bin/activate; fi
  - "python --version"
  - "pip install -r requirements.pip"
  - "pip install -r requirements-dev.pip"
  - "pip install overalls"
  - "npm install"
before_script:
  - "psql -c \"create user go with createdb password 'go';\" -U postgres"
  - "psql -c 'create database go owner go;' -U postgres"
  - "export VUMITEST_REDIS_DB=1 VUMIGO_TEST_DB=postgres VUMI_TEST_TIMEOUT=10"
  - "export PYTHONPATH=."
  - "django-admin.py syncdb --migrate --noinput --settings=go.testsettings"
  - "pip list"
  # To see what version of Riak we're running and check that it's happy.
  - riak version
  - sudo riak-admin member-status
script:
  - ./run-tests.sh
  - grunt test
after_script:
  - "psql -c 'drop database go;' -U postgres"
  - "psql -c 'drop user go;' -U postgres"
after_success:
  - if [ -z "$NO_COVERAGE" ]; then overalls --py --lcov mochacov.lcov --lcov coverage/*/lcov.info; fi
