language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
env:
  - RIAK_VERSION="1.4.12" VUMITEST_REDIS_DB=1 VUMIGO_TEST_DB=postgres VUMI_TEST_TIMEOUT=10
matrix:
  include:
    # Test against Riak 2.1.1.
    # This is a separate matrix inclusion to avoid spawning unnecessary builds.
    - python: "2.7"
      env: RIAK_VERSION="2.1.1" VUMITEST_REDIS_DB=1 VUMIGO_TEST_DB=postgres VUMI_TEST_TIMEOUT=10

services:
  - postgresql
  - redis-server

before_install:
  # Set up an appropriate version of Riak.
  - utils/setup_travis_riak.sh "${RIAK_VERSION}"
install:
  - "pip install -r requirements.pip"
  - "pip install -r requirements-dev.pip"
  - "pip install overalls"
  - "npm install"

before_script:
  - "psql -c \"create user go with createdb password 'go';\" -U postgres"
  - "psql -c 'create database go owner go;' -U postgres"
  - "export PYTHONPATH=."
  - "django-admin.py syncdb --migrate --noinput --settings=go.testsettings"
  - "pip list"
  # To see what version of Riak we're running and check that it's happy.
  - $HOME/riak/bin/riak version
  - $HOME/riak/bin/riak-admin member-status
script:
  - ./run-tests.sh
  - grunt test

after_success:
  - overalls --py --lcov mochacov.lcov --lcov coverage/*/lcov.info
